packages:
  - apps/*
  - packages/*

# Dependency Resolution (https://pnpm.io/settings#dependency-resolution)
overrides:
  # https://github.com/openapi-ts/openapi-typescript/issues/2723
  # https://github.com/openapi-ts/openapi-typescript/pull/2774
  # https://github.com/openapi-ts/openapi-typescript/pull/2818
  "openapi-typescript>typescript": "^5.x || ^6.x"
minimumReleaseAge: 1440 # 1 day in minutes
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyExclude:
  # semver began publishing packages with provenance in 7.5.1. However, their v6
  # packages (including 6.3.1 which was published after 7.5.1) do not. Since
  # 6.3.1 was published in 2023-07-10, and no known vulnerability has been
  # reported, it is ignored.
  #
  # https://github.com/pnpm/pnpm/issues/10202
  - semver@6.3.1
blockExoticSubdeps: true

# Build settings (https://pnpm.io/settings#build-settings)
verifyDepsBeforeRun: install
strictDepBuilds: true
allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true

# Other Settings (https://pnpm.io/settings#other-settings)
shellEmulator: true

# Settings documented elsewhere (https://pnpm.io/settings#settings-documented-elsewhere)
patchedDependencies:
  # Only updating types. This PR has already been merged
  # https://github.com/MikeMcl/decimal.js/pull/264
  decimal.js: patches/decimal.js.patch
