import type { Tag } from "libexif-wasm";

// https://github.com/libexif/libexif/blob/b9b7f3c08c1b6812ad3b9d62227ad9527ab9385a/libexif/exif-entry.c#L671
const EXIF_TAG_VALUE_MAP = {
  PLANAR_CONFIGURATION: {
    "Chunky format": 0,
    "Planar format": 1,
  },
  SENSING_METHOD: {
    "Not defined": 1,
    "One-chip color area sensor": 2,
    "Two-chip color area sensor": 3,
    "Three-chip color area sensor": 4,
    "Color sequential area sensor": 5,
    "Trilinear sensor": 7,
    "Color sequential linear sensor": 8,
  },
  ORIENTATION: {
    "Top-left": 1,
    "Top-right": 2,
    "Bottom-right": 3,
    "Bottom-left": 4,
    "Left-top": 5,
    "Right-top": 6,
    "Right-bottom": 7,
    "Left-bottom": 8,
  },
  YCBCR_POSITIONING: {
    Centered: 1,
    "Co-sited": 2,
  },
  PHOTOMETRIC_INTERPRETATION: {
    "Reversed mono": 0,
    "Normal mono": 1,
    RGB: 2,
    Palette: 3,
    CMYK: 5,
    YCbCr: 6,
    CieLAB: 8,
  },
  CUSTOM_RENDERED: {
    "Normal process": 0,
    "Custom process": 1,
  },
  EXPOSURE_MODE: {
    "Auto exposure": 0,
    "Manual exposure": 1,
    "Auto bracket": 2,
  },
  WHITE_BALANCE: {
    "Auto white balance": 0,
    "Manual white balance": 1,
  },
  SCENE_CAPTURE_TYPE: {
    Standard: 0,
    Landscape: 1,
    Portrait: 2,
    "Night scene": 3,
  },
  GAIN_CONTROL: {
    Normal: 0,
    "Low gain up": 1,
    "High gain up": 2,
    "Low gain down": 3,
    "High gain down": 4,
  },
  SATURATION: {
    Normal: 0,
    "Low saturation": 1,
    "High saturation": 2,
  },
  CONTRAST: {
    Normal: 0,
    Soft: 1,
    Hard: 2,
  },
  SHARPNESS: {
    Normal: 0,
    Soft: 1,
    Hard: 2,
  },
  METERING_MODE: {
    Unknown: 0,
    Average: 1,
    "Center-weighted average": 2,
    Spot: 3,
    "Multi spot": 4,
    Pattern: 5,
    Partial: 6,
    Other: 255,
  },
  COMPRESSION: {
    Uncompressed: 1,
    "LZW compression": 5,
    "JPEG compression": 6,
    "Deflate/ZIP compression": 8,
    "PackBits compression": 32773,
  },
  LIGHT_SOURCE: {
    Unknown: 0,
    Daylight: 1,
    Fluorescent: 2,
    "Tungsten incandescent light": 3,
    Flash: 4,
    "Fine weather": 9,
    "Cloudy weather": 10,
    Shade: 11,
    "Daylight fluorescent": 12,
    "Day white fluorescent": 13,
    "Cool white fluorescent": 14,
    "White fluorescent": 15,
    "Standard light A": 17,
    "Standard light B": 18,
    "Standard light C": 19,
    D55: 20,
    D65: 21,
    D75: 22,
    "ISO studio tungsten": 24,
    Other: 255,
  },
  FOCAL_PLANE_RESOLUTION_UNIT: {
    Inch: 2,
    Centimeter: 3,
  },
  RESOLUTION_UNIT: {
    Inch: 2,
    Centimeter: 3,
  },
  EXPOSURE_PROGRAM: {
    "Not defined": 0,
    Manual: 1,
    "Normal program": 2,
    "Aperture priority": 3,
    "Shutter priority": 4,
    "Creative program (biased toward depth of field)": 5,
    "Creative program (biased toward fast shutter speed)": 6,
    "Portrait mode (for closeup photos with the background out of focus)": 7,
    "Landscape mode (for landscape photos with the background in focus)": 8,
  },
  SENSITIVITY_TYPE: {
    Unknown: 0,
    "Standard output sensitivity (SOS)": 1,
    "Recommended exposure index (REI)": 2,
    "ISO speed": 3,
    "Standard output sensitivity (SOS) and recommended exposure index (REI)": 4,
    "Standard output sensitivity (SOS) and ISO speed": 5,
    "Recommended exposure index (REI) and ISO speed": 6,
    "Standard output sensitivity (SOS) and recommended exposure index (REI) and ISO speed": 7,
  },
  FLASH: {
    "Flash did not fire": 0x0000,
    "Flash fired": 0x0001,
    "Strobe return light not detected": 0x0005,
    "Strobe return light detected": 0x0007,
    "Flash fired, compulsory flash mode": 0x0009,
    "Flash fired, compulsory flash mode, return light not detected": 0x000d,
    "Flash fired, compulsory flash mode, return light detected": 0x000f,
    "Flash did not fire, compulsory flash mode": 0x0010,
    "Flash did not fire, auto mode": 0x0018,
    "Flash fired, auto mode": 0x0019,
    "Flash fired, auto mode, return light not detected": 0x001d,
    "Flash fired, auto mode, return light detected": 0x001f,
    "No flash function": 0x0020,
    "Flash fired, red-eye reduction mode": 0x0041,
    "Flash fired, red-eye reduction mode, return light not detected": 0x0045,
    "Flash fired, red-eye reduction mode, return light detected": 0x0047,
    "Flash fired, compulsory flash mode, red-eye reduction mode": 0x0049,
    "Flash fired, compulsory flash mode, red-eye reduction mode, return light not detected": 0x004d,
    "Flash fired, compulsory flash mode, red-eye reduction mode, return light detected": 0x004f,
    "Flash did not fire, auto mode, red-eye reduction mode": 0x0058,
    "Flash fired, auto mode, red-eye reduction mode": 0x0059,
    "Flash fired, auto mode, return light not detected, red-eye reduction mode": 0x005d,
    "Flash fired, auto mode, return light detected, red-eye reduction mode": 0x005f,
  },
  SUBJECT_DISTANCE_RANGE: {
    Unknown: 0,
    Macro: 1,
    "Close view": 2,
    "Distant view": 3,
  },
  COLOR_SPACE: {
    sRGB: 1,
    "Adobe RGB": 2,
    Uncalibrated: 0xffff,
  },
  COMPOSITE_IMAGE: {
    Unknown: 0,
    "Not a composite image": 1,
    "General composite image": 2,
    "Composite image captured while shooting": 3,
  },
} satisfies Partial<Record<Tag, Record<string, number>>>;

export { EXIF_TAG_VALUE_MAP };
