[build]
base = "apps/api"
publish = "dist"
command = "pnpm --workspace-root exec turbo run build --filter=@exifi/api..."
ignore = "corepack pnpm --workspace-root exec turbo query affected --packages @exifi/api --base=$CACHED_COMMIT_REF --head=$COMMIT_REF --exit-code"

[[plugins]]
package = "netlify-plugin-emsdk"
[plugins.inputs]
version = "6.0.10"
